# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - release
  - deploy

variables:
  # Project variables
  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-keycloak-realm-builder

  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit


# Only run pipeline when pushing a tag or a branch.
# This is a workaround for a bug causing detached pipelines on MRs
# See: https://gitlab.com/gitlab-org/gitlab/-/issues/34756
#      https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

include:
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/autopub.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-build.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-release.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/config-updater-meta.v1.yml

# Lint stage
#############

.lint-default: &lint-default
  stage: lint
  needs: []
  tags:
    - docker
  image: python:3.8
  before_script:
    - pip install poetry pre-commit
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    - pre-commit install

lint-all:
  <<: *lint-default
  script:
    - pre-commit run --all-files

# Test stage
############

Test RealmBuilder:
  stage: test
  needs: ["Build RealmBuilder"]
  image:
    name: ${IMAGE_SHA}
    entrypoint: [""]
  variables:
    KEYCLOAK_ADMIN_PASSWORD: "123"
  tags:
    - docker
  script:
    - python3 main.py


# Release stage
###############

Release to Dev:
  extends: .release-to-dev
  needs: ["Release version"]
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-dev

Release to Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-test

Release to Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-prod
