# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - coverage
  - release
  - deploy


variables:
  REALMBUILDER_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/realm-builder:${CI_COMMIT_SHA}
  REALMBUILDER_RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-keycloak-realm-builder

  INTEGRATIONBUILDER_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/integration-builder:${CI_COMMIT_SHA}
  INTEGRATIONBUILDER_RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-keycloak-integration-builder

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

  PYTEST_COV_MODULE: .
  PYTEST_COV_FAIL_UNDER: 0

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit


workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID


include:
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/autopub.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-build-meta.v2.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-release-meta.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/config-updater-meta.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/python/pytest.v1.yml



# Lint stage
#############

.lint-default: &lint-default
  stage: lint
  needs: []
  image: python:3.10
  before_script:
    - pip install poetry pre-commit
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    - pre-commit install

lint-all:
  <<: *lint-default
  script:
    - pre-commit run --all-files


# Build stage
#############

Build RealmBuilder:
  extends: .build-docker
  variables:
    CI_IMAGE: ${REALMBUILDER_IMAGE_SHA}


Build IntegrationBuilder:
  extends: .build-docker
  variables:
    CONTEXT: ${CI_PROJECT_DIR}/integration
    DOCKERFILE: ${CI_PROJECT_DIR}/integration/Dockerfile
    CI_IMAGE: ${INTEGRATIONBUILDER_IMAGE_SHA}


# Test stage
############

Test RealmBuilder:
  stage: test
  needs: ["Build RealmBuilder"]
  image:
    name: ${REALMBUILDER_IMAGE_SHA}
    entrypoint: [""]
  variables:
    KEYCLOAK_ADMIN_PASSWORD: "123"
  script:
    - python3 main.py


# Release stage
###############

Release RealmBuilder master:
  extends: .release-master
  variables:
    CI_IMAGE: ${REALMBUILDER_IMAGE_SHA}
    RELEASE_IMAGE: ${REALMBUILDER_RELEASE_REGISTRY_IMAGE}

Release RealmBuilder version:
  extends: .release-version
  variables:
    CI_IMAGE: ${REALMBUILDER_IMAGE_SHA}
    RELEASE_IMAGE: ${REALMBUILDER_RELEASE_REGISTRY_IMAGE}


Release IntegrationBuilder master:
  extends: .release-master
  variables:
    CI_IMAGE: ${INTEGRATIONBUILDER_IMAGE_SHA}
    RELEASE_IMAGE: ${INTEGRATIONBUILDER_RELEASE_REGISTRY_IMAGE}

Release IntegrationBuilder version:
  extends: .release-version
  variables:
    CI_IMAGE: ${INTEGRATIONBUILDER_IMAGE_SHA}
    RELEASE_IMAGE: ${INTEGRATIONBUILDER_RELEASE_REGISTRY_IMAGE}

# Deploy stage
##############

Deploy to Dev:
  extends: .release-to-dev
  needs: ["Release RealmBuilder version"]
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-dev

Deploy to Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-test

Deploy to Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/realmbuilder/update-prod
