# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
#    depends_on:
#      - keycloak-db
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      DB_VENDOR: H2
#      DB_ADDR: "keycloak-db"
#      DB_USER: keycloak
#      DB_PASSWORD: keycloak
#      DB_SCHEMA: public
#      DB_DATABASE: keycloak
      # PROXY_ADDRESS_FORWARDING: 'true'
      # KEYCLOAK_FRONTEND_URL: https://proxy/auth
      # KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - type: bind
        source: ./realm.json
        target: /tmp/realm.json
#  keycloak-db:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: keycloak
